language: node_js
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: 'AKIAJUAZQ4QZNKW2RDFA'
  secret_access_key: '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'
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "elasticbeanstalk-us-east-2-010372538723"
  region: "US East (Ohio)"
